# Generated by Django 4.2.18 on 2025-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="job_title",
            field=models.ManyToManyField(
                related_name="team_members", to="website.jobtitle"
            ),
        ),
    ]
