# Generated by Django 4.2.18 on 2025-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.IntegerField(
                choices=[(1, "کاربر"), (2, "ادمین"), (3, "سوپر وایزر")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="کاربر جدید", max_length=250),
        ),
    ]
