# Generated by Django 4.2.18 on 2025-03-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryfeature",
            options={},
        ),
        migrations.AlterModelOptions(
            name="featureoption",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productcategorymodel",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterField(
            model_name="categoryfeature",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productcategorymodel",
            ),
        ),
    ]
