# Generated by Django 4.2.19 on 2025-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['status', '-created_date', '-avg_rate'], name='shop_produc_status_d10af8_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['price'], name='shop_produc_price_f806fe_idx'),
        ),
    ]
