# Generated by Django 4.2.18 on 2025-03-31 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_categoryfeature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryfeature",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="categoryfeature",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="featureoption",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="shop.categoryfeature",
            ),
        ),
        migrations.AlterField(
            model_name="featureoption",
            name="value",
            field=models.CharField(max_length=255),
        ),
    ]
