# Generated by Django 4.2.18 on 2025-04-22 11:07

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_categoryfeature_is_required_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productfeature",
            options={},
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categoryfeature",
            ),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.featureoption",
            ),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="shop.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="avg_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="brief_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop.productcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="discount_percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "نمایش"),
                    (2, "عدم نمایش"),
                    (3, "به صورت کامل ایجاد نشده"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
