# Generated by Django 4.2.18 on 2025-05-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_productfeature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategorymodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="shop.productcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="productcategorymodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
