# Generated by Django 4.2.18 on 2025-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_productcategorymodel_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "منتشر شده"),
                    (2, "عدم انتشار"),
                    (3, "به صورت کامل ایجاد نشده"),
                ],
                default=2,
            ),
        ),
    ]
