# Generated by Django 4.2.18 on 2025-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_productmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                default="/default/product-image.png", upload_to="product/img/"
            ),
        ),
    ]
