# Generated by Django 4.2.18 on 2025-07-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_wishlistproductmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistproductmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_wishlists",
                to="shop.productmodel",
            ),
        ),
    ]
