# Generated by Django 4.2.18 on 2025-07-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_productcategorymodel_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlistproductmodel",
            options={"ordering": ["-id"]},
        ),
    ]
