# Generated by Django 4.2.18 on 2025-04-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponmodel",
            options={"ordering": ["-created_date"]},
        ),
    ]
