# Generated by Django 4.2.18 on 2025-07-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("order", "0003_couponmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="payment.paymentmodel",
            ),
        ),
    ]
